name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - "custom-tooltip-using-angular-cdk/**"
      - ".github/workflows/main.yml"
      - "!**/*.md"
      - "!**/*.gitignore"

# setting permissions for GitHub Pages deployment
permissions:
  id-token: write   # allow generating OpenID Connect OIDC tokens for authentication with GitHub Pages
  pages: write      # allow publishing to GitHub Pages

env:
  # using custom base href for GitHub Pages deployment
  # because the repo is hosted under a subpath e.g. https://username.github.io/angular-tooltip-examples/
  BASE_HREF: "/angular-tooltip-examples/"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./custom-tooltip-using-angular-cdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js environment
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22.20.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v4.2.0
        with:
          version: 10.18.1

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build --base-href=${{ env.BASE_HREF }}

      - name: Test the project
        run: pnpm test

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: ./custom-tooltip-using-angular-cdk/dist/custom-tooltip-using-angular-cdk/browser

  deploy:
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
